### ISSUE TITLE
Can't easily use to replace sendmail for PHP apps

### ISSUE THREAD

**Issue by geerlingguy** [mailhog/mhsendmail#2]
I'm trying to use mhsendmail as a sendmail replacement for some Drupal sites, and when I try sending emails using Drupal's built-in email functionality (with PHP's `sendmail_path` defined as `/opt/mailhog/mhsendmail`, where the binary is located), I get the following error in the logs:

```
flag provided but not defined: -femail@example.com
Usage of /opt/mailhog/mhsendmail:
  -from="nobody@example": SMTP sender
  -smtp-addr="localhost:1025": SMTP server address
```

It looks like mhsendmail expects a nice `-from=address` format, but Drupal (and many other PHP apps I've encountered use `-faddress` to provide a from email address.

Can you add support for this format, so mhsendmail can be more of a drop-in replacement for sendmail?

**Comment by ian-kent** [comment]
Thanks @geerlingguy - I'd assumed things like sendmail path would be configurable, then I looked at the Drupal source... hope this fix works!

**Comment by geerlingguy** [comment]
> then I looked at the Drupal source...

Haha, for most things, Drupal's wonderfully configurable. But not sendmail :P
