### ISSUE TITLE
New tagged release?

### ISSUE THREAD

**Issue by pbowyer** [mailhog/mhsendmail#8]
Any chance we could have a new tagged release please, or confirmation that the recommended way to install is to do so from source?

https://github.com/geerlingguy/ansible-role-mailhog/issues/3 has been waiting on a MailHog 0.2.0 tagged release since Oct 2015, and as I'm waiting on the change in that issue, figured I 'd ask :)

**Comment by lmakarov** [comment]
I'm in the same boat. Waiting for a fresh release tag as well.

**Comment by ian-kent** [comment]
Done, sorry it took so long!

**Comment by pbowyer** [comment]
Thanks Ian, and thanks for writing and maintaining such a fantastically useful piece of software!
